spring:
  application:
    name: zenith-discord-bot
  main:
    banner-mode: OFF
  data:
    mongodb:
      uri: ${SPRING_MONGODB_URI:mongodb://localhost:27017/zenith}
      auto-index-creation: true

sentry:
  dsn: ${SENTRY_DSN:}
  debug: false
  send-default-pii: ${SENTRY_SEND_DEFAULT_PII:false}
  max-breadcrumbs: 200
  traces-sample-rate: 0.1
  profile-session-sample-rate: 0.01
  enable-backpressure-handling: true
  logging:
    minimum-event-level: WARN
    minimum-breadcrumb-level: INFO
  logs:
    enabled: ${SENTRY_LOGS_ENABLED:true}
  enable-spotlight: false

discord:
  bot:
    token: ${DISCORD_BOT_TOKEN:}

zenith:
  member-of-the-week:
    guild-id: "1520153947644493905"
    channel-id: "1529817686110896169"
    log-channel-id: "1529817716880441414"
    role-id: "1526317499862356018"
    timezone: "Europe/Warsaw"
    cron: "0 0 18 ? * MON"
    voting-duration: 24h
